@BASE_URL = http://localhost:3333


# @name create-account
POST {{BASE_URL}}/users
Content-Type: application/json

{
  "name": "Walter",
  "email": "walter@wbdigitalsolutions.com",
  "password": "123456a@d"
}

###


# @name get all users
GET {{BASE_URL}}/users
