@BASE_URL = http://localhost:3333


# @name create-account
POST {{BASE_URL}}/users
Content-Type: application/json

{
  "name": "Bruno",
  "email": "bruno@bruno.com",
  "password": "123456@a",
  "licenses": [
    {
      "amount": 1000,
      "method": "Visa",
      "valid": true
    }
  ]
}

###
# @name create-device
POST {{BASE_URL}}/devices
Content-Type: application/json

{
  "name": "Device 1",
  "userId": "0bc5216d-d2c9-406a-92f4-c12fd1f62fa5",
  "hostname": "hostname",
  "macNumber": "macNumber",
  "os": "os",
  "version": "version"
}

###


# @name get-all-users
GET {{BASE_URL}}/users


###

# @name get-all-users-with-valid-licenses
GET {{BASE_URL}}/users/valid-licenses



###

# @name auth
POST {{BASE_URL}}/auth
Content-Type: application/json

{
  "email": "bruno@bruno.com",
  "password": "123456@a"
}  